apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azuret0services.crossplane.com
  labels:
    provider: azure
    services: t0services  
spec:
  compositeTypeRef:
    apiVersion: crossplane.com/v1alpha1
    kind: compositet0service
  patchSets:
  - name: Metadata
    patches:
    - fromFieldPath: metadata.labels
    - fromFieldPath: metadata.annotations
  resources:
    - name: resourcegroup
      base:
        apiVersion: azure.jet.crossplane.io/v1alpha2
        kind: ResourceGroup
        metadata:
          labels:
            provider: azure
            vnet: crossplane-poc-new
        spec:
          forProvider:
            location: South India
          providerConfigRef:
            name: az-provider-config
    - name: vnet
      base:
        apiVersion: network.azure.jet.crossplane.io/v1alpha2
        kind: VirtualNetwork
        metadata:
          labels:
            provider: azure
            vnet: crossplane-poc-new
        spec:
          forProvider:
            resourceGroupNameSelector:
              matchControllerRef: true
              matchLabels:
                provider: azure
                vnet: crossplane-poc-new
            location: South India
            addressSpace:
              - 10.2.0.0/24
          providerConfigRef:
            name: az-provider-config
    - name: subnet
      base:
        apiVersion: network.azure.jet.crossplane.io/v1alpha2
        kind: Subnet
        metadata:
          labels:
            provider: azure
            vnet: crossplane-poc-new
        spec:
          forProvider:
            addressPrefix: 10.2.0.0/25
            resourceGroupNameSelector:
              matchControllerRef: true
              matchLabels:
                provider: azure
                vnet: crossplane-poc-new
            virtualNetworkNameSelector:
              matchControllerRef: true
              matchLabels:
                provider: azure
                vnet: crossplane-poc-new
          providerConfigRef:
            name: az-provider-config
      patches:
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.id
        toFieldPath: status.subnetId
    - name: nic
      base:
        apiVersion: network.azure.jet.crossplane.io/v1alpha2
        kind: NetworkInterface
        metadata:
          name: t0nic
          labels:
            provider: azure
            vnet: crossplane-poc-new
        spec:
          providerConfigRef:
            name: az-provider-config
          forProvider:
            ipConfiguration:
              - name: aznic
                privateIpAddressAllocation: Dynamic
                subnetIdSelector:
                  matchControllerRef: true
                  matchLabels:
                    provider: azure
                    vnet: crossplane-poc-new                
            location: South India
            name: nic
            resourceGroupNameSelector:
              matchControllerRef: true
              matchLabels:
                provider: azure
                vnet: crossplane-poc-new
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: status.subnetId
        toFieldPath: spec.forProvider.ipConfiguration.subnetId
      - type: ToCompositeFieldPath
        fromFieldPath: status.atProvider.id
        toFieldPath: status.networkInterfaceId
    - name: vm
      base:
        apiVersion: compute.azure.jet.crossplane.io/v1alpha1
        kind: LinuxVirtualMachine
        metadata:
          name: t0vm
          labels:
            provider: azure
            vnet: crossplane-poc-new
        spec:
          providerConfigRef:
            name: az-provider-config
          forProvider:
            disablePasswordAuthentication: false
            platform_fault_domain: 1
            adminUsername: azuser
            adminPasswordSecretRef:
              key: password
              name: vm-creds
              namespace: default
            location: South India
            name: vm
            sourceImageReference:
              - offer: UbuntuServer
                publisher: Canonical
                sku: 18.04-LTS
                version: latest
            osDisk:
              - caching: ReadWrite
                storageAccountType: Standard_LRS
                diskSizeGb: 30
            size: Standard_B1s
            resourceGroupNameSelector:
              matchControllerRef: true
              matchLabels:
                provider: azure
                vnet: crossplane-poc-new
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "status.networkInterfaceId"
        toFieldPath: "spec.forProvider.networkInterfaceIds[0]"
        # - type: PatchSet
        #   patchSetName: Metadata
        #   fromFieldPath: "spec.parameters.nic"
        #   toFieldPath: "spec.forProvider.networkInterfaceIds"    
    # - name: postgresql
    #   base:
    #     apiVersion: database.azure.crossplane.io/v1beta1
    #     kind: PostgreSQLServer
    #     metadata:
    #       name: postgres-psql
    #       labels:
    #         provider: azure
    #         vnet: crossplane-poc-new
    #     spec:
    #       forProvider:
    #         administratorLogin: myadmin
    #         resourceGroupNameSelector:
    #           matchControllerRef: true
    #           matchLabels:
    #             provider: azure
    #             vnet: crossplane-poc-new
    #         location: South India
    #         minimalTlsVersion: TLS1_2
    #         sslEnforcement: Enabled
    #         version: "9.6"
    #         sku:
    #           # Note that Basic servers do not support virtual network rules
    #           tier: GeneralPurpose
    #           capacity: 2
    #           family: Gen5
    #         storageProfile:
    #           storageMB: 20480
    #       writeConnectionSecretToRef:
    #         namespace: crossplane-system
    #         name: postgres-psql
    #       providerConfigRef:
    #         name: az-provider-config
    # - name: postgresqlconfig
    #   base:
    #     apiVersion: database.azure.crossplane.io/v1beta1
    #     kind: PostgreSQLServerConfiguration
    #     metadata:
    #       name: postgres-psql-configuration
    #     spec:
    #       providerConfigRef:
    #         name: az-provider-config
    #       forProvider:
    #         resourceGroupNameSelector:
    #           matchControllerRef: true
    #           matchLabels:
    #             provider: azure
    #             vnet: crossplane-poc-new
    #         serverNameRef:
    #           name: postgres-psql
    #         name: max_wal_senders
    #         value: "12"
    
    
    # db-server
    # - name: postgresqlserver
    #   base:
    #     apiVersion: database.azure.crossplane.io/v1beta1
    #     kind: PostgreSQLServer
    #     spec:
    #       forProvider:
    #         createMode: Default
    #         administratorLogin: myadmin
    #         resourceGroupNameSelector:
    #           matchControllerRef: true
    #         minimalTlsVersion: TLS1_2
    #         sslEnforcement: Enabled
    #         sku:
    #           tier: GeneralPurpose
    #           capacity: 2
    #           family: Gen5  
    #         storageProfile:
    #           backupRetentionDays: 35
    #           geoRedundantBackup: Disabled
    #           storageAutogrow: Disabled
    #       writeConnectionSecretToRef:
    #         namespace: crossplane-system
    #       providerConfigRef:
    #         name: default
    #   patches:
    #   - type: PatchSet
    #     patchSetName: Metadata
    #   - fromFieldPath: "metadata.uid"
    #     toFieldPath: "spec.writeConnectionSecretToRef.name"
    #     transforms:
    #     - type: string
    #       string:
    #         fmt: "postgresqlserver-admin-%s"
    #   - fromFieldPath: "spec.parameters.version"
    #     toFieldPath: "spec.forProvider.version"
    #   - fromFieldPath: "spec.parameters.location"
    #     toFieldPath: "spec.forProvider.location"
    #   - fromFieldPath: "spec.parameters.storageGB"
    #     toFieldPath: "spec.forProvider.storageProfile.storageMB"
    #     transforms:
    #       - type: math
    #         math:
    #           multiply: 1024
    # # sql-provider config with db-server connection
    # - name: sqlproviderconfig
    #   base:
    #     apiVersion: postgresql.sql.crossplane.io/v1alpha1
    #     kind: ProviderConfig
    #     spec:
    #       credentials:
    #         source: PostgreSQLConnectionSecret
    #         connectionSecretRef:
    #           namespace: crossplane-system
    #   patches:
    #   - type: PatchSet
    #     patchSetName: Metadata
    #   - fromFieldPath: "metadata.uid"
    #     toFieldPath: "metadata.name"
    #     transforms:
    #     - type: string
    #       string:
    #         fmt: "sql-provider-config-%s"
    #   - fromFieldPath: "metadata.uid"
    #     toFieldPath: "spec.credentials.connectionSecretRef.name"
    #     transforms:
    #     - type: string
    #       string:
    #         fmt: "postgresqlserver-admin-%s"
    #   readinessChecks:
    #   - type: None
    # database on the db-server
    # - name: postgresqldatabase
    #   base:
    #     apiVersion: postgresql.sql.crossplane.io/v1alpha1
    #     kind: Database
    #     spec:
    #       forProvider: {}
    #   patches:
    #   - type: PatchSet
    #     patchSetName: Metadata
    #   - fromFieldPath: "spec.parameters.dbName"
    #     toFieldPath: "metadata.annotations[crossplane.io/external-name]"
    #   - fromFieldPath: "metadata.uid"
    #     toFieldPath: "spec.providerConfigRef.name"
    #     transforms:
    #     - type: string
    #       string:
    #         fmt: "sql-provider-config-%s"
    #   connectionDetails:
    #     - type: FromFieldPath
    #       name: database
    #       fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
    # connection role
    # - name: postgresqlrole
    #   base:
    #     apiVersion: postgresql.sql.crossplane.io/v1alpha1
    #     kind: Role
    #     spec:
    #       forProvider:
    #         connectionLimit: 10
    #         privileges:
    #           login: true
    #       writeConnectionSecretToRef:
    #         namespace: crossplane-system
    #   patches:
    #   - type: PatchSet
    #     patchSetName: Metadata
    #   - fromFieldPath: "metadata.uid"
    #     toFieldPath: "spec.providerConfigRef.name"
    #     transforms:
    #     - type: string
    #       string:
    #         fmt: "sql-provider-config-%s"
    #   - fromFieldPath: "metadata.uid"
    #     toFieldPath: "spec.writeConnectionSecretToRef.name"
    #     transforms:
    #     - type: string
    #       string:
    #         fmt: "postgresqlserver-connect-%s"
    #   - fromFieldPath: "spec.parameters.dbName"
    #     toFieldPath: "metadata.annotations[crossplane.io/external-name]"
    #     transforms:
    #     - type: string
    #       string:
    #         fmt: "connection-%s"
    #   connectionDetails:
    #   - fromConnectionSecretKey: username
    #   - fromConnectionSecretKey: password
    #   - name: hostname
    #     fromConnectionSecretKey: endpoint
    #   - fromConnectionSecretKey: port
    # # grants for connection role
    # - name: postgresqlgrant
    #   base:
    #     apiVersion: postgresql.sql.crossplane.io/v1alpha1
    #     kind: Grant
    #     spec:
    #       forProvider:
    #         privileges:
    #           - CREATE
    #           - CONNECT
    #           - TEMPORARY
    #         roleSelector:
    #           matchControllerRef: true
    #         databaseSelector:
    #           matchControllerRef: true
    #   patches:
    #   - type: PatchSet
    #     patchSetName: Metadata
    #   - fromFieldPath: "metadata.uid"
    #     toFieldPath: "spec.providerConfigRef.name"
    #     transforms:
    #     - type: string
    #       string:
    #         fmt: "sql-provider-config-%s"