apiVersion: network.azure.jet.crossplane.io/v1alpha2
kind: VirtualNetwork
metadata:
  name: crossplane-poc-new
  namespace: default
  labels:
    provider: azure
    vnet: crossplane-poc-new
spec:
  forProvider:
    resourceGroupNameSelector:
      matchControllerRef: true
      matchLabels:
        provider: azure
        vnet: crossplane-poc-new
    location: South India
    addressSpace:
      - 10.2.0.0/24
  providerConfigRef:
    name: az-provider-config